sudo: required
services:
  - docker

before_install:
  - docker build -t gomurali/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run gomurali/react-test npm test -- --coverage

after_success:
  - docker build -t gomurali/multi-client ./client
  - docker build -t gomurali/multi-nginx ./nginx
  - docker build -t gomurali/multi-server ./server
  - docker build -t gomurali/multi-worker ./worker
  #login to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push gomurali/multi-client
  - docker push gomurali/multi-nginx
  - docker push gomurali/multi-server
  - docker push gomurali/multi-worker